"""Resolve a repo-relative path from a test that must run in BOTH trees.

``scripts/`` is not an importable package, so a test for one of its files loads
it by path. That is fine in the private checkout and a **session-killer** in the
public export, where the test ships and the script does not: the load runs at
module scope, so the failure is a *collection* error, and pytest aborts the whole
session on those. Measured on ``spectraMR`` run 33881085296 (2026-09-04): three
such files raised ``FileNotFoundError``, pytest reported ``Interrupted: 3 errors
during collection``, and **zero** of the suite's tests executed -- after 37m25s
spent collecting. Nothing downstream of pytest ran either, so ``make``'s next
line (mutation testing) and the coverage upload had never once fired.

``tests/unit/scripts/test_dicom_to_nifti.py`` already carried the sibling of this
note for the *dependency* variant (#804): "``_load_script`` EXECUTES it at module
scope, so a missing dep aborts collection for all of tests/unit". The missing
**script** variant is the same hazard reached by a different absence, and it was
unguarded.

The hard part is not skipping -- it is skipping *only* when the absence is
explained. A bare ``if not path.exists(): skip`` also swallows a genuine deletion
in the private tree, which is the ``importorskip``-on-an-in-tree-module trap: a
broken checker becomes a green run. So absence is **reported, never inferred**:

============================  =========================  =====================
script present?               tree                       result
============================  =========================  =====================
yes                           either                     the path
no                            private checkout           **fail**, loudly
no                            public export              skip, naming why
no                            unrecognisable             **fail**, loudly
============================  =========================  =====================

and "which tree" is *derived* rather than declared, in the shape
``tests/architecture/test_no_stale_package_name.py::_active_roots`` established:
the export is by construction the tree containing nothing outside
``scripts/release/public_allowlist.txt``, so a tree is the export exactly when no
unselected file under ``scripts/`` survives in it. That cannot be flipped by the
deletion this guard must stay sensitive to -- the private checkout carries 431
files under ``scripts/`` against 25 allowlist entries selecting them, so removing
one leaves several hundred others still unselected and the answer still "private".

Every function here is pure and total in its ``root``, so the tests drive them
with synthetic trees rather than with whatever tree the suite happens to run in
-- the only way to exercise the export branch from the private checkout.

``scripts/`` was the first subject, not the only one: the export also drops
``experiments/`` wholesale, and a test that reads one arm by path fails there for
the same reason and with the same two wrong answers. So the resolver is
:func:`require_repo_file` and takes any repo-relative path -- the tree-identity
question it asks about ``scripts/`` is evidence about the *tree*, not about the
subject. A test that asserts over a whole corpus has no single path to name;
:func:`skip_if_public_export` is that case, and it is keyed on the same derived
verdict rather than on the corpus being empty.
"""

from __future__ import annotations

import functools
import importlib.util
import sys
from pathlib import Path
from types import ModuleType

import pytest

#: ``tests/utils/repo_scripts.py`` -> the checkout root.
REPO_ROOT = Path(__file__).resolve().parents[2]

#: Ships in the export itself (the allowlist selects ``scripts/release/``), which
#: is what lets a test consult it from either tree.
ALLOWLIST_REL = "scripts/release/public_allowlist.txt"

#: Never evidence of anything: bytecode is regenerated by whoever imported last,
#: and an export carrying it is a contaminated export, not a private tree.
_IGNORED_DIRS = frozenset({"__pycache__"})


def selects(entry: str, rel_path: str) -> bool:
    """Does one allowlist line select ``rel_path``?

    The file mixes three line shapes -- a comment, a directory prefix ending in
    ``/``, and an exact path -- and trailing comments share a line with a real
    entry (``scripts/ci/check_layering.sh    # PASS, ...``), so the comment is
    stripped before the match rather than the line being skipped for containing
    a ``#``.
    """
    entry = entry.split("#", 1)[0].strip()
    if not entry:
        return False
    if entry.endswith("/"):
        return rel_path.startswith(entry)
    return rel_path == entry


def unselected_scripts(root: Path) -> tuple[str, ...]:
    """Files under ``root/scripts`` that the allowlist does **not** select.

    Returns the evidence rather than a verdict so a failure message can name it
    and so the export branch is falsifiable: an empty result is the claim "this
    tree ships only what it published", and the caller can print what broke it.
    """
    allowlist = root / ALLOWLIST_REL
    if not allowlist.exists():
        return ()
    entries = allowlist.read_text(encoding="utf-8").splitlines()
    unselected: list[str] = []
    for path in sorted((root / "scripts").rglob("*")):
        if not path.is_file() or _IGNORED_DIRS & set(path.parts):
            continue
        rel = path.relative_to(root).as_posix()
        if not any(selects(entry, rel) for entry in entries):
            unselected.append(rel)
    return tuple(unselected)


def is_public_export(root: Path = REPO_ROOT) -> bool:
    """Is ``root`` the published tree rather than the private checkout?

    False when the allowlist is absent: that tree is neither, and a guard that
    cannot say *why* a file is missing has not earned the right to skip.
    """
    if not (root / ALLOWLIST_REL).exists():
        return False
    return not unselected_scripts(root)


@functools.lru_cache(maxsize=1)
def _export_verdict() -> bool:
    """``is_public_export`` for the live tree; cached -- it walks ``scripts/``."""
    return is_public_export()


def require_repo_file(rel_path: str, root: Path | None = None) -> Path:
    """The absolute path to ``rel_path``, or an explained skip / a loud failure.

    ``rel_path`` is any repo-relative path -- ``scripts/ci/gate.py`` or
    ``experiments/inprogress/<cohort>/<arm>.yaml``. Safe at module scope: the
    skip is ``allow_module_level`` so the export stops at "1 skipped" instead of
    "errors during collection". Inside a test body it is an ordinary skip, which
    is what a *partial* file needs -- the tests whose subject still ships keep
    running.
    """
    live = root is None
    base = REPO_ROOT if live else root
    script = base / rel_path
    if script.exists():
        return script

    exported = _export_verdict() if live else is_public_export(base)
    if exported:
        pytest.skip(
            f"{rel_path} does not ship in the public export "
            "(scripts/release/public_allowlist.txt does not select it), so there "
            "is nothing here to test",
            allow_module_level=True,
        )
    unselected = unselected_scripts(base)
    pytest.fail(
        f"{rel_path} is missing from a tree that is NOT the public export "
        f"({len(unselected)} unselected file(s) under scripts/ are still present, "
        f"e.g. {unselected[:3] or '-- and no allowlist was found either'}). "
        "Refusing to skip: this is a deletion or a bad checkout, not a "
        "publication boundary.",
        pytrace=False,
    )
    raise AssertionError("unreachable")  # pragma: no cover - pytest.fail raises


def load_script_module(rel_path: str, module_name: str, root: Path | None = None) -> ModuleType:
    """Import a ``scripts/`` file by path, guarded by :func:`require_repo_file`.

    Registered in ``sys.modules`` before execution so a script defining classes
    that get pickled, or doing a self-import, resolves to this same module.
    """
    script = require_repo_file(rel_path, root)
    spec = importlib.util.spec_from_file_location(module_name, script)
    if spec is None or spec.loader is None:  # pragma: no cover - defensive
        raise ImportError(f"cannot build an import spec for {script}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module


def skip_if_public_export(reason: str, root: Path | None = None) -> None:
    """Skip when this tree is the published export; do nothing otherwise.

    The counterpart to :func:`require_repo_file` for a test that asserts over a
    whole *corpus* rather than reading one path -- "at least 30 arms declare a
    workflow", "every cohort member agrees on the sampler". The export drops
    ``experiments/`` wholesale, so there is no single missing file to name, and
    the assertion fails on the empty set instead of raising ``FileNotFoundError``.

    Keying the skip on emptiness instead -- ``if not arms: skip`` -- is the shape
    that silently swallows a genuine drain of the cohort in the private tree,
    which is the *only* thing these tripwires exist to catch. So ask which tree,
    never whether the corpus is there.
    """
    exported = _export_verdict() if root is None else is_public_export(root)
    if exported:
        pytest.skip(f"public export: {reason}")
